---
- name: Set up WebServers nodes
  hosts: WebServers # WebServers is the group in the inventory file. all refers to all groups in the inventory file.
  become: true
  roles:
    - nginx
    - devops
    - firewall
    - docker
    - nodejs
