---
- name: Ensure group 'sudo' exists
  become: true
  ansible.builtin.group:
    name: sudo
    state: present

- name: Set hashed password for 'devops' user
  ansible.builtin.set_fact:
    devops_pass: "{{ 'devops' | password_hash('sha512') }}"

- name: Add devops user
  become: true
  ansible.builtin.user:
    name: devops
    groups: sudo
    append: true
    shell: /bin/bash
    create_home: true
    password: "{{ devops_pass }}"
