- name: Install Node.js 22.x
  become: true
  changed_when: false
  ansible.builtin.shell: |
    # curl -fsSL {{ nodejs_rhel_url }} | bash -
    set -o pipefail && curl -fsSL {{ nodejs_ubuntu_url }} | bash -
  args:
    executable: /bin/bash

- name: Install Node.js y npm
  become: true
  ansible.builtin.package:
    name: nodejs
    state: present
