---
- name: Install UFW
  become: true
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow SSH (22) port
  become: true
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow puerto HTTP (80) port
  become: true
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow puerto HTTPS (443) port
  become: true
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Allow UFW (be sure that the firewall is enabled)
  become: true
  community.general.ufw:
    state: enabled
    policy: allow
