---
- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Add Docker GPG de Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: true

- name: Enable and Start Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add vagrant and devops users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}" # use variables defined in docker/defaults/main.yml
  notify: Restart Docker

- name: Check users of 'docker' group
  shell: getent group | grep docker
  register: docker_group_output
  ignore_errors: true

- name: Show members of 'docker' group
  debug:
    msg: "{{ docker_group_output.stdout | default('docker group does not exists') }}"
